common:
  # Training settings
  batch_size: 128            # Training batch size
  epochs: 1000               # Number of training epochs
  learning_rate: 0.0003      # Learning rate for the optimizer
  
  # Model settings
  backbone: ResNet34         # Backbone network architecture
  feature_dim: 128           # Feature dimension
  
  # Loss settings
  instance: true             # Whether to use instance loss
  cluster: true              # Whether to use clustering loss
  variational: true          # Whether to use variational loss
  var_weight: 0.5            # Variational weight, default is 0.5
  instance_temperature: 0.5  # Temperature for instance loss
  cluster_temperature: 1.0   # Temperature for cluster loss
  
  # Optimization settings
  weight_decay: 0            # Weight decay (L2 regularization), default is 0
  use_gradnorm: true         # Whether to use gradient clipping
  max_norm: 1.0              # Maximum norm for gradient clipping
  
  # Checkpoint settings
  checkpoint: true           # Whether to save checkpoints
  reload: true               # Whether to reload from the last checkpoint
  save_model: true           # Whether to save the model
  
  # Experiment settings
  project: CVC               # Project name for tracking
  seed: 42                   # Random seed for reproducibility

datasets:
  cifar10:
    class_num: 10            # Number of classes for CIFAR-10
    s: 0.5                   # Color jitter strength
    blur: false              # Whether to apply Gaussian blur
    
  cifar100:
    class_num: 20            # Number of classes for CIFAR-100
    var_weight: 0.25         # Variational weight for CIFAR-100
    s: 0.5                   # Color jitter strength
    blur: false              # Whether to apply Gaussian blur
    
  imagenet10:
    class_num: 10            # Number of classes for ImageNet10
    s: 1.0                   # Color jitter strength
    blur: true               # Whether to apply Gaussian blur

  tiny-imagenet:
    class_num: 200
    s: 0.5
    blur: false